import Head from "next/head";
import React from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Daily Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blog-logo-1.png" className="text-white" />
      </Head>

      <Navbar />
      <main className="flex justify-center items-center flex-col">
        <div className="w-11/12 lg:w-10/12">{children}</div>
      </main>
      <Footer />
    </>
  );
};

export default Layout;
